### ISSUE TITLE
Release build produces GL error on Linux

### ISSUE THREAD

**Issue by maacl** [paulbutcher/electron-template#1]
I am on Ubuntu 19.04.

When running a release build of the example app (built as per README) I get the following error and a blank window:

```
➜  myapp-linux-x64 ./myapp 
[16495:1203/100546.725691:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[16495:1203/100546.737550:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
  
```

**Comment by paulbutcher** [comment]
Some quick Googling reveals a number of reports of similar problems with some Linux systems:

https://stackoverflow.com/questions/37725345/display-error-with-visual-studio-code-under-ubuntu
https://stackoverflow.com/questions/58347778/electron-fix-errorbuffer-manager-cc488-displaycompositorgl-error-gl-inv

It seems like adding ``--disable-gpu`` when starting might be a workaround?

**Comment by maacl** [comment]
Thanks but passing `--disable-gpu` to the native binary doesn't make any difference,

**Comment by paulbutcher** [comment]
My feeling is that this is most likely an Electron or Chrome issue and best followed up by asking the Electron community for help, so I'm going to close this bug. Please feel free to reopen if you feel that it's an issue with the template, however.
