### ISSUE TITLE
Support inline styles

### ISSUE THREAD

**Issue by brianium** [paulbutcher/electron-template#6]
I have grown fond of [herb](https://github.com/roosta/herb) for styling, and the current content security policy for the index html files does not allow it.

Is there a reason for this?

I was able to get this working by adding
`; style-src 'unsafe-inline'` to the meta tag for `Content-Security-Policy`.

Would this be welcome as a PR? Or does that violate the spirit of a template? Just curious.

Very grateful for this sane starting point for electron apps in ClojureScript 🙇

**Comment by paulbutcher** [comment]
Glad you find the template helpful!

As its name suggest `unsafe-inline` carries security risks. If this is a valid tradeoff for your particular use case, then go for it. But I'm not sure that a template should encourage unnecessarily weakened security?
